"""add age column to users table

Revision ID: a1813bb87835
Revises: a1b2c3d4e5f6
Create Date: 2026-05-19 16:37:43.638764

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1813bb87835"
down_revision: str | Sequence[str] | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_secom_users_email")
    op.execute("DROP INDEX IF EXISTS ix_secom_users_username")
    op.execute("DROP TABLE IF EXISTS secom_users CASCADE")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "secom_users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "username", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=5), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("secom_users_pkey")),
    )
    op.create_index(
        op.f("ix_secom_users_username"), "secom_users", ["username"], unique=True
    )
    op.create_index(op.f("ix_secom_users_email"), "secom_users", ["email"], unique=True)
    # ### end Alembic commands ###
